name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build AAR files
      run: |
        ./gradlew :library:assembleRelease
        ./gradlew :library:assembleDebug
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: |
          ./library/build/outputs/aar/library-release.aar
          ./library/build/outputs/aar/library-debug.aar
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          ## MicroInteractions ${{ github.ref_name }}
          
          ### Installation
          ```gradle
          dependencies {
              implementation("com.github.gay00ung:MicroInteractions:${{ github.ref_name }}")
          }
          ```
          
          ### Assets
          - `library-release.aar` - Release build
          - `library-debug.aar` - Debug build with debugging symbols